version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    container_name: elasticsearch
    restart: always
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      -  /home/merxer_io/efk-k8s/data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
    logging:
      driver: "json-file"
      options:
        max-size: "1G"
        max-file: "2"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.1
    container_name: kibana
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - esnet
    depends_on:
      - elasticsearch
    logging:
      driver: "json-file"
      options:
        max-size: "1G"
        max-file: "2"


networks:
  esnet:
    external:
      name: esnet
